version: 3.0.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Debug

#before_build:
#  - nuget restore
  
build:
  project: Interlinq.sln

after_build:
  - ps: .\nuget\pack.ps1

test: off

artifacts:
  - path: InterLinq\bin\Debug\InterLinq.dll
    name: InterLinq.dll
  - path: InterLinq\bin\Debug\InterLinq.pdb
    name: InterLinq.pdb
  - path: '**\DotNetProjects.*.nupkg'

#uncomment to publish to NuGet
deploy:
  provider: NuGet
  api_key:
    secure: OrhpK2cLXXcoWW+hU6xAv3eeKIbATEFbenteoFsi9EfM1yyDof6ZuNKAsA3Vy6vb
  artifact: /.*\.nupkg/
  
  
  